### PR TITLE
Add plantseg datasets

### PR DESCRIPTION
**Pull request by constantinpape**

### CODE REVIEW

**Comment by constantinpape** [comment]
Hey @FynnBe, can we just merge this and will it be displayed on bioimagei.io then?
Sorry, I am not up-to-date on how the partner mechanism currently works.

**Comment by FynnBe** [comment]
almost, we also need to trigger the main wf in the collection repo (this will be automatically triggered soonish)

**Comment by FynnBe** [comment]
Actually great that we try this now... as we use https://raw.githubusercontent.com/ilastik/bioimage-io-resources/main/collection.yaml as source in the collection repo this deployment cannot happen immediately... we would need to delay the collection repo trigger by 5-10 min...

Mayb we can just increase the cron schedule frequency (twice a day atm) for the collection main wf?

**Comment by FynnBe** [comment]
or we are ok with <=12h and can always trigger it manually otherwise...

**Comment by constantinpape** [comment]
> Actually great that we try this now... as we use https://raw.githubusercontent.com/ilastik/bioimage-io-resources/main/collection.yaml as source in the collection repo this deployment cannot happen immediately... we would need to delay the collection repo trigger by 5-10 min...

Note that this is only an issue for repeated changes; if you do a single update it will be reflected in `raw.githubusercontent` immediately; but then it will take 5-10 min for the next changes to get through.
(At least I think that's how it works.)

**Comment by FynnBe** [comment]
ah, I see.. yes, this update was quick, the collection main wf ran and then successfully triggered ilastik's test resource workflow https://github.com/ilastik/bioimage-io-resources/runs/5413634344?check_suite_focus=true

successfull cirlce!

**Comment by FynnBe** [comment]
> Note that this is only an issue for repeated changes;

then we probably should add that automatic trigger...

**Pull request merged**
