### PR TITLE
Update manifest.bioimage.io.yaml

### PR DESCRIPTION
**Pull request by FynnBe**
the ilastik application was missing a lot of fields....  I suppose we didn't rely on them so far.
Additionally to filling some missing values this PR adds `supported_weight_formats` to `config` as discussed in https://github.com/bioimage-io/spec-bioimage-io/issues/130#issuecomment-866692339

### CODE REVIEW

**Comment by oeway** [comment]
For the moment, this is a special case, this application is an bioengine app, the manifest compiler will take other fields from the source file: https://raw.githubusercontent.com/ilastik/bioimage-io-models/master/src/Ilastik-app.imjoy.html So we don't need to fill the fields in the manifes yaml. If you want to make changes, please change the corresponding fields Ilastik-app.imjoy.html file directly. In the yaml, we only need `source`, `id` and `config.supported_weight_formats`.

However, I am thinking whether we need to change this, the issue is that if we don't take the fields from the bioengine app, we will have two source of fields (the RDF and the bioengine app) that maybe different from each other. Perhaps we should stick the current format and think about it later.

**Comment by FynnBe** [comment]
so we should add `config: supported_weight_formats` to https://github.com/ilastik/bioimage-io-models/blob/master/src/Ilastik-app.imjoy.html (for now)?

**Comment by oeway** [comment]
> so we should add `config: supported_weight_formats` to https://github.com/ilastik/bioimage-io-models/blob/master/src/Ilastik-app.imjoy.html (for now)?

Nope, place it in the YAML together with the `source` key.

**Comment by oeway** [comment]
BTW, do you have a newer version of this: https://gist.github.com/oeway/2d4b5899424a14d8e90ad908d4cec364/

We need to expand the support for other ilastik models,  the current one only support the UNet2DNucleiBroad model.

**Comment by oeway** [comment]
There is a better solution here which is 1) keep all the RDF fields in yaml 2) change the source to a website URL, e.g. to a specific page to https://ilastik.org  or here by enabling github pages 3) in the page we add buttons for running models via bioengine. Would this make more sense?

**Comment by FynnBe** [comment]
> BTW, do you have a newer version of this: https://gist.github.com/oeway/2d4b5899424a14d8e90ad908d4cec364/
> 
> We need to expand the support for other ilastik models, the current one only support the UNet2DNucleiBroad model.

yes, this is still WIP though and will take some more weeks to be finalized

**Pull request closed without merging**
